Machine Learning With Python: Save And Load Trained Model

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [5]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [6]:
model.coef_

array([135.78767123])

In [7]:
model.intercept_

180616.43835616432

In [8]:
model.predict([[5000]])

array([859554.79452055])

### Save Model To a File Using Python Pickle

In [9]:
import pickle

In [10]:
with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)

Load Saved Model

In [11]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [18]:
mp.coef_

array([135.78767123])

In [19]:
mp.intercept_

180616.43835616432

In [15]:
mp.predict([[5000]])

array([859554.79452055])

same as previous

### Save Model To a File Using Python joblib

In [23]:
import joblib

In [24]:
joblib.dump(model, 'model_joblib')

['model_joblib']

Load Saved Model

In [27]:
joblib.load('model_joblib')

LinearRegression()

In [28]:
mj = joblib.load('model_joblib')

In [29]:
mj.coef_

array([135.78767123])

In [30]:
mj.intercept_

180616.43835616432

In [31]:
mp.predict([[5000]])

array([859554.79452055])