In [1]:
import numpy as np

In [2]:
a = np.array([3, 5, 7])
a

array([3, 5, 7])

In [3]:
a.ndim # dimensions of array 'a'

1

In [4]:
a.itemsize # space occupy to every single object of an array: 8 bytes

8

In [5]:
a.dtype

dtype('int64')

In [6]:
 a.shape

(3,)

In [7]:
a = np.array([3, 5, 7], float)

In [8]:
a.dtype, a.itemsize

(dtype('float64'), 8)

In [9]:
a

array([3., 5., 7.])

In [10]:
b = np.array([[1,2], [3,4], [5,6]])

In [11]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
b.itemsize, b.ndim, b.dtype, b.shape

(8, 2, dtype('int64'), (3, 2))

In [13]:
b.shape

(3, 2)

In [14]:
b.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
b.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [16]:
b.ravel()

array([1, 2, 3, 4, 5, 6])

In [17]:
b.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [18]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
a, b

(array([3., 5., 7.]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [20]:
a = np.array([3, 5, 7], complex)

In [21]:
a

array([3.+0.j, 5.+0.j, 7.+0.j])

In [22]:
b = np.array([[1,2], [3,4], [5,6]], complex)

In [23]:
b

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

#### zeros(), ones() functions: 

In [24]:
O = np.zeros((3,3))

In [25]:
O

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
I = np.ones((3,4))

In [27]:
I

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
I.reshape(2,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [29]:
I.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
I.reshape(4,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
l = range(5)
l

range(0, 5)

In [34]:
l[0], l[1], l[-1]

(0, 1, 4)

In [35]:
np.arange(1,5)

array([1, 2, 3, 4])

In [39]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [40]:
np.linspace(1, 5, 5)

array([1., 2., 3., 4., 5.])

In [41]:
np.linspace(1, 5, 6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [42]:
np.linspace(1, 5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [45]:
a.sum(axis = 0)

(15+0j)

In [47]:
# a.sum(axis = 1) # AxisError: axis 1 is out of bounds for array of dimension 1

In [48]:
a

array([3.+0.j, 5.+0.j, 7.+0.j])

In [49]:
b

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [50]:
b.sum(axis = 0)

array([ 9.+0.j, 12.+0.j])

In [51]:
b.sum(axis = 1)

array([ 3.+0.j,  7.+0.j, 11.+0.j])

In [52]:
np.sqrt(a)

array([1.73205081+0.j, 2.23606798+0.j, 2.64575131+0.j])

In [53]:
np.sqrt(b)

array([[1.        +0.j, 1.41421356+0.j],
       [1.73205081+0.j, 2.        +0.j],
       [2.23606798+0.j, 2.44948974+0.j]])

#### product of matrices

In [54]:
a.dot(b)

array([53.+0.j, 68.+0.j])

In [56]:
# b.dot(a) # ValueError: shapes (3,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)

In [57]:
np.dot(a,b)

array([53.+0.j, 68.+0.j])