In [1]:
import numpy as np

In [2]:
a = np.array([[3,4,5], [2,5,6],[5,7,8]])
a

array([[3, 4, 5],
       [2, 5, 6],
       [5, 7, 8]])

In [3]:
a[0]

array([3, 4, 5])

In [4]:
a[1], a[-1]

(array([2, 5, 6]), array([5, 7, 8]))

In [5]:
a[1,2]

6

In [6]:
a[0,0]

3

In [7]:
a[0,0], a[1,1],a[2,2]

(3, 5, 8)

In [8]:
a[0,0],a[0,1],a[0,2]

(3, 4, 5)

In [9]:
a[0,0], a[1,0], a[2,0]

(3, 2, 5)

In [10]:
a[0:1, 1]

array([4])

In [25]:
a[0:1, 2]

array([5])

In [14]:
a[0:1, 2], a[1:1, 1], a[2:0, 0]

(array([5]), array([], dtype=int64), array([], dtype=int64))

In [24]:
 a[0:1, 2]

array([5])

In [29]:
a

array([[3, 4, 5],
       [2, 5, 6],
       [5, 7, 8]])

In [30]:
a[0:2,2]

array([5, 6])

In [31]:
a[0:3,2]

array([5, 6, 8])

In [33]:
a[2,0], a[1,1], a[0,2]

(5, 5, 5)

In [36]:
a[0:1,2]

array([5])

In [41]:
a[0:1,0], a[0:1,1], a[0:1,2]

(array([3]), array([4]), array([5]))

In [59]:
a[1:1,0], a[1:1,1], a[1:1,2]

(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))

In [60]:
a[0:3,0], a[0:3,1], a[0:3,2]

(array([3, 2, 5]), array([4, 5, 7]), array([5, 6, 8]))

In [62]:
a[:, 1:3]

array([[4, 5],
       [5, 6],
       [7, 8]])

In [63]:
a[:, 1:2]

array([[4],
       [5],
       [7]])

In [66]:
a[:,0], a[:,1], a[:,2]

(array([3, 2, 5]), array([4, 5, 7]), array([5, 6, 8]))

In [67]:
a[:,2], a[:,1], a[:,0]

(array([5, 6, 8]), array([4, 5, 7]), array([3, 2, 5]))

#### stacking

In [74]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

In [75]:
a, b 

(array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]]))

In [77]:
np.vstack((a,b)) # v for vertical stack

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [79]:
np.hstack((a,b)) # h for horizontal stack

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [80]:
np.vstack((a[2], b[1]))

array([[4, 5],
       [8, 9]])

In [81]:
np.hstack((a[2], b[1]))

array([4, 5, 8, 9])

In [82]:
np.vstack((a[2], b[1])).reshape(4,1)

array([[4],
       [5],
       [8],
       [9]])

#### slicing

In [87]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [91]:
result = np.hsplit(a,3)
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [89]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [92]:
result[0], result[-1]

(array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]]))

In [94]:
result = np.vsplit(a.reshape(3,10),3)
result

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [95]:
result[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [96]:
result[1].reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#### Indexing

In [98]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
b = a>4

In [100]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [103]:
a[b] = 6
a[b]

array([6, 6, 6, 6, 6, 6, 6])

In [104]:
a

array([[0, 1, 2, 3],
       [4, 6, 6, 6],
       [6, 6, 6, 6]])

In [105]:
a[b] = -1
a[b]

array([-1, -1, -1, -1, -1, -1, -1])

In [106]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [107]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])