In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv('codebasics_multi_variable_data.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [5]:
df.bedrooms.median()

3.5

In [7]:
# to make it integer
import math 
median_bedroom = math.floor(df.bedrooms.median())
median_bedroom

3

In [8]:
df.fillna(median_bedroom)

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [9]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [12]:
df.bedrooms = df.bedrooms.fillna(median_bedroom)
df.bedrooms

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [13]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [14]:
reg = linear_model.LinearRegression()

## f = m1.x + m2.y + m3.z + c
## price = m1*area + m2*bedrooms + m3*age + constant

In [15]:
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [16]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [17]:
reg.intercept_

383725.00000000006

In [18]:
reg.predict([[3000, 3, 40]])

array([444400.])

In [19]:
reg.predict([[3000, 3, 15]])

array([615025.])

In [20]:
reg.predict([[2500, 4, 5]])

array([588625.])

In [21]:
# line methods
price = (137.25*2500) + (-26025*4) + (-6825*5) + (383725.00000000006)
price

588625.0