In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
# from word2number import w2n # imported @ [20]; 

In [2]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [5]:
df.experience = df.experience.fillna(0)

In [6]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0          0                    8.0                           9      50000
1          0                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [8]:
# df.	test_score(out of 10) = df.	test_score(out of 10).fillna(0)
# SyntaxError: invalid syntax

#### need to rename columns:

In [15]:
df.rename(columns = {'test_score(out of 10)': 'test_score', 'interview_score(out of 10)': 'interview_score', 'salary($)': 'salary'}, inplace = True)

In [17]:
df

experience  test_score  interview_score  salary
0          0         8.0                9   50000
1          0         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [20]:
test_score_fill = df.test_score.median()
test_score_fill
# df.test_score = df.test_score.fillna(....?) # ..? == test_score_fill

8.0

In [23]:
df.test_score = df.test_score.fillna(test_score_fill)

In [24]:
df

experience  test_score  interview_score  salary
0          0         8.0                9   50000
1          0         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

#### to fit data into model we need value in type 'number type' not in 'string type'. 
#### So, convert  years of experience value into number of year from given string.......

In [34]:
from word2number import w2n

In [35]:
df.experience

0         0
1         0
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [36]:
exp_list = df.experience.tolist()
exp_list

[0, 0, 'five', 'two', 'seven', 'three', 'ten', 'eleven']

exp_num_list = w2n.word_to_num(exp_list)
exp_num_list
ValueError: Type of input is not string! Please enter a valid number word (eg. 'two million twenty three thousand and forty nine')

In [42]:
w2n.word_to_num('one')

1

In [43]:
for value in exp_list:
    num = w2n.word_to_num(str(value))
    print(num)

0
0
5
2
7
3
10
11


In [44]:
exp_num_list = []
for value in exp_list:
    num = w2n.word_to_num(str(value))
    exp_num_list.append(num)

In [45]:
exp_num_list

[0, 0, 5, 2, 7, 3, 10, 11]

In [46]:
df

experience  test_score  interview_score  salary
0          0         8.0                9   50000
1          0         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [47]:
exp_num_col = np.array(exp_num_list)

In [48]:
exp_num_col

array([ 0,  0,  5,  2,  7,  3, 10, 11])

In [49]:
exp_num_col.reshape(8,1)

array([[ 0],
       [ 0],
       [ 5],
       [ 2],
       [ 7],
       [ 3],
       [10],
       [11]])

In [50]:
exp_num_col

array([ 0,  0,  5,  2,  7,  3, 10, 11])

In [53]:
col_exp = np.vstack(exp_num_col)
col_exp

array([[ 0],
       [ 0],
       [ 5],
       [ 2],
       [ 7],
       [ 3],
       [10],
       [11]])

In [54]:
df['expeince_num'] = col_exp

In [59]:
df

experience  test_score  interview_score  salary  expeince_num
0          0         8.0                9   50000             0
1          0         8.0                6   45000             0
2       five         6.0                7   60000             5
3        two        10.0               10   65000             2
4      seven         9.0                6   70000             7
5      three         7.0               10   62000             3
6        ten         8.0                7   72000            10
7     eleven         7.0                8   80000            11

In [61]:
df['experience'] = df['expeince_num'].values

In [62]:
df

experience  test_score  interview_score  salary  expeince_num
0           0         8.0                9   50000             0
1           0         8.0                6   45000             0
2           5         6.0                7   60000             5
3           2        10.0               10   65000             2
4           7         9.0                6   70000             7
5           3         7.0               10   62000             3
6          10         8.0                7   72000            10
7          11         7.0                8   80000            11

In [63]:
df.drop('expeince_num', axis=1, inplace=True)

In [64]:
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

Finally got the structured data/ clean data/ workable data;;;

### Now train the model based on DataFrame df

In [65]:
reg = linear_model.LinearRegression()

## f = m1.x + m2.y + m3.z + c
## salary = m1*experience + m2*test_score + m3*interview_score + constant

In [69]:
reg.fit(df[['experience', 'test_score', 'interview_score']], df.salary)

LinearRegression()

In [70]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [71]:
reg.intercept_

17737.263464337695

##### Now model is trained and ready to predict salary

1. person_1 =  2 years experince, 9 test score and 6 interview score

In [74]:
reg.predict([[2, 9, 6]])

array([53205.96797671])

2. person_2 =  12 years experince, 10 test score and 10 interview score

In [75]:
reg.predict([[12, 10, 10]])

array([92002.18340611])