In [1]:
import numpy as np
a = np.array([[1,2,3.0], [10,20,30]])
print(a)

[[ 1.  2.  3.]
 [10. 20. 30.]]


In [2]:
import numpy as np
a = np.array([[1,2,3], [10,20,30]])
print(a)

[[ 1  2  3]
 [10 20 30]]


In [3]:
# dimesion of the array:
a.ndim

2

In [4]:
import numpy as np
a = np.array([[1,2,3], [10,20]])
print(a) 

[list([1, 2, 3]) list([10, 20])]


/home/vins/Workspace/Py/python/venv/lib/python3.6/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


(1, None)

In [5]:
import numpy as np
a = np.array([[1,2,3.0], [10,20]])
print(a)

[list([1, 2, 3.0]) list([10, 20])]


/home/vins/Workspace/Py/python/venv/lib/python3.6/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


In [6]:
a.ndim

1

In [7]:
a = np.array([1,2,3])
b = np.array([[1,2,3], [10,20,30]])
c = np.array([ [ [1,2,3],[2,3,4] ],[ [10,20,30],[11,22,33] ] ])

print(a)
print(b)
print(c)

[1 2 3]
[[ 1  2  3]
 [10 20 30]]
[[[ 1  2  3]
  [ 2  3  4]]

 [[10 20 30]
  [11 22 33]]]


In [8]:
a.ndim, b.ndim, c.ndim

(1, 2, 3)

In [9]:
# shape or structure of the array
a.shape, b.shape, c.shape

((3,), (2, 3), (2, 2, 3))

In [ ]:
a = np.array([ [1,2,3], [2,3,4], [10,20,30] ])
b = np.array([[1,2,3], [3,4,5], [4,5,3], [2,3,4], [10,20,30] ][10,20,30]])
c = np.array([ [ [1,2,3],[2,3,4] ],[ [10,20,30],[11,22,33] ] ])

print(a)
print(b)
print(c)